name: build and push binary to release

# Controls when the action will run.
on:
  push:
    branches:
      - main
  release:
    types: [created,published] # 表示在创建新的 Release 时触发

# Allows you to run this workflow manually from the Actions tab
  # 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 设置go环境
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
        cache-dependency-path: "go.sum"
    - name: 编译后端
      run: |
        go mod tidy -v